In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(pd.read_excel("https://www.bls.gov/lau/laucnty21.xlsx"))

In [3]:
df.drop(index=df.index[:5], axis=0, inplace=True)

In [4]:
df.drop(index=df.tail(3).index,axis = 0, inplace=True)

In [5]:
df.drop(columns="Unnamed: 5", inplace=True)

In [6]:
df.columns = ["LAUS_code", "state_fips", "county_fips", "county_state", "year", "labor_force", "employed", "unemployed", "unemployment_rate"]

In [7]:
df['fips'] = df['state_fips'] + df['county_fips']

In [8]:
df

,LAUS_code,state_fips,county_fips,county_state,year,labor_force,employed,unemployed,unemployment_rate,fips
5,CN0100100000000,01,001,"Autauga County, AL",2021,26341,25599,742,2.8,01001
6,CN0100300000000,01,003,"Baldwin County, AL",2021,99427,96481,2946,3,01003
7,CN0100500000000,01,005,"Barbour County, AL",2021,8197,7728,469,5.7,01005
8,CN0100700000000,01,007,"Bibb County, AL",2021,8560,8262,298,3.5,01007
9,CN0100900000000,01,009,"Blount County, AL",2021,25127,24529,598,2.4,01009
...,...,...,...,...,...,...,...,...,...,...
3220,CN7214500000000,72,145,"Vega Baja Municipio, PR",2021,14185,12742,1443,10.2,72145
3221,CN7214700000000,72,147,"Vieques Municipio, PR",2021,2775,2435,340,12.3,72147
3222,CN7214900000000,72,149,"Villalba Municipio, PR",2021,7700,6807,893,11.6,72149
3223,CN7215100000000,72,151,"Yabucoa Municipio, PR",2021,9164,8217,947,10.3,72151
3224,CN7215300000000,72,153,"Yauco Municipio, PR",2021,10213,9014,1199,11.7,72153

In [9]:
print(pd.io.sql.get_schema(df, "us_employment_data"))

CREATE TABLE "us_employment_data" (
"LAUS_code" TEXT,
  "state_fips" TEXT,
  "county_fips" TEXT,
  "county_state" TEXT,
  "year" TEXT,
  "labor_force" INTEGER,
  "employed" INTEGER,
  "unemployed" INTEGER,
  "unemployment_rate" TEXT,
  "fips" TEXT
)

In [10]:
df.year = pd.to_numeric(df.year)
df.unemployment_rate = pd.to_numeric(df.unemployment_rate)

In [11]:
print(pd.io.sql.get_schema(df, "us_employment_data"))

CREATE TABLE "us_employment_data" (
"LAUS_code" TEXT,
  "state_fips" TEXT,
  "county_fips" TEXT,
  "county_state" TEXT,
  "year" INTEGER,
  "labor_force" INTEGER,
  "employed" INTEGER,
  "unemployed" INTEGER,
  "unemployment_rate" REAL,
  "fips" TEXT
)

In [12]:
df.to_csv(f"/Users/alvin/Documents/projects/project_de-zoomcamp/01-ingestion/data/us_employment_{df.year[6]}.csv", index=None, header=True)

In [13]:
df_csv = pd.DataFrame(pd.read_csv(f"/Users/alvin/Documents/projects/project_de-zoomcamp/01-ingestion/data/us_employment_{df.year[6]}.csv"))

In [14]:
df_csv

,LAUS_code,state_fips,county_fips,county_state,year,labor_force,employed,unemployed,unemployment_rate,fips
0,CN0100100000000,1,1,"Autauga County, AL",2021,26341,25599,742,2.8,1001
1,CN0100300000000,1,3,"Baldwin County, AL",2021,99427,96481,2946,3.0,1003
2,CN0100500000000,1,5,"Barbour County, AL",2021,8197,7728,469,5.7,1005
3,CN0100700000000,1,7,"Bibb County, AL",2021,8560,8262,298,3.5,1007
4,CN0100900000000,1,9,"Blount County, AL",2021,25127,24529,598,2.4,1009
...,...,...,...,...,...,...,...,...,...,...
3215,CN7214500000000,72,145,"Vega Baja Municipio, PR",2021,14185,12742,1443,10.2,72145
3216,CN7214700000000,72,147,"Vieques Municipio, PR",2021,2775,2435,340,12.3,72147
3217,CN7214900000000,72,149,"Villalba Municipio, PR",2021,7700,6807,893,11.6,72149
3218,CN7215100000000,72,151,"Yabucoa Municipio, PR",2021,9164,8217,947,10.3,72151
3219,CN7215300000000,72,153,"Yauco Municipio, PR",2021,10213,9014,1199,11.7,72153